export { default as Home } from './Home/Home';
export { default as Login } from './Login/Login';
export { default as Catalog } from './Catalog/Catalog';
export { default as Profile } from './Profile/Profile';
export { default as Product } from './Product/Product';
export { default as SignUp } from './Register/Register';
export { default as NotFound } from './NotFound/NotFound';
export { default as Forbidden } from './Forbidden/Forbidden';
export { default as Unauthorized } from './Unauthorized/Unauthorized';
